

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/venv  # Exclude the virtual environment from volume mount
    environment:
      - ENV=development
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - tldr-network
    depends_on: []

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules from volume mount
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000
      - VITE_PUBLIC_API_KEY=${API_AUTH_KEY}
    networks:
      - tldr-network
    depends_on:
      - backend

networks:
  tldr-network:
    driver: bridge

volumes:
  backend-venv:
  frontend-node-modules:
